spring.application.name=spring-banking-backend
server.port=8085

spring.datasource.url=jdbc:h2:mem:bank
spring.h2.console.enabled=true

openai.model=gpt-3.5-turbo
openai.api.key=${OPENAI_API_KEY}
openai.api.url=https://api.openai.com/v1/chat/completions

jwt.secret=8zT5xR2pQ9mN4vL7kH3jG6fD1sA0wE8yU5bI2oZ9tV4rC7nK3mM6pL1hJ0gF5dBs

telegram.bot.username=BankBotMundiabot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
